# Generated by Django 5.2.15 on 2026-06-24 05:31

from django.db import migrations, models
from django.utils.text import slugify


def populate_unique_slugs(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')

    for post in Post.objects.all().order_by('id'):
        base_slug = slugify(post.title) or 'post'
        slug = base_slug
        counter = 1

        while Post.objects.exclude(pk=post.pk).filter(slug=slug).exists():
            slug = f'{base_slug}-{counter}'
            counter += 1

        post.slug = slug
        post.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.RunPython(populate_unique_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
